eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
#app
spring:
  profiles: pd-crm-z
  application:
    name: cust-center
server:
  port: 9001

---
#web
spring:
  profiles: pd-crm-z
  application:
    name: crm-web
server:
  port: 8001
  
  
---
#zuul
spring:
  profiles: pd-crm-z
  application:
    name: cust-zuul

server:
  port: 7001

zuul:
  routes:
    hello-service:
      path: /cust-center
      serviceId: cust-center

